dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - { python: "2.7", env: DJANGO=1.11 }
    - { python: "3.4", env: DJANGO=2.0 }
    - { python: "nightly", env: DJANGO=2.2 }

install:
  - pip install -r requirements.txt
  - pip install 'py>1.7' 'pytest>4' 'pytest-django' 'pytest-cov'
  - pip install coveralls

script: python setup.py test

after_success:
  coveralls
